### ISSUE TITLE
The Posts Page: View Latest Posts

### ISSUE THREAD

**Issue by Graciekan21** [Graciekan21/arts#13]
User Story
As a **user,** I can **see all the most recent posts, sorted by creation date,** so I **stay up to date with the newest content**
**Acceptance criteria**

- Display an array of posts  of posts using  filters

- 

**Tasks**

- [ ] Add PostsPage component 
- [ ]  Add the no-results.png to assets folder
- [ ] Spread a loading spinner
