### ISSUE TITLE
The Post Page: Delete comments

### ISSUE THREAD

**Issue by Graciekan21** [Graciekan21/arts#22]
User Story
**As an owner** of a comment, **I can edit** my comment **to fix or update it.**

**Acceptance criteria**

- Can edit they owner comments and update them

**Tasks**

- [ ] Check if the user is the owner.
- [ ] Create a comment handleDelete function
- [ ] Decrement post's comments_count by one
- [ ] filter out the deleted comment from the array
- [ ] Update both setPost and setComments
